<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An error occurred while installing Rights.' => 'Произошла ошибка при установке модуля Rights',
  'Application authorization manager must extend the RDbAuthManager class.' => 'Класс менеджера авторизации приложения должен наследовать класс RDbAuthManager',
  'Application web user must extend the RWebUser class.' => 'Класс веб-пользователя приложения должен наследовать класс RWebUser',
  'Congratulations!' => 'Поздравляем!',
  'Error' => 'Ошибка',
  'Install Rights' => 'Установить модуль Rights',
  'No' => 'Нет',
  'Notice: All your existing data will be lost.' => 'Помните, все существующие данные будут уничтожены',
  'Please confirm if you wish to reinstall.' => 'Подтвердите, что хотите переустановить модуль',
  'Please try again or consult the documentation.' => 'Попытайтесь еще раз или обратитесь к документации',
  'Rights has been installed succesfully.' => 'Модуль Rights успешно установлен',
  'Rights is already installed!' => 'Модуль Rights уже установлен',
  'Yes' => 'Да',
  'You can start by generating your authorization items' => 'Вы можете начать с генерации элементов авторизации',
  'You must be logged in to install Rights.' => 'Вы должны быть залогинены для установки модуля Rights',
  'here' => 'здесь',
);